global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi_model_serving'
    static_configs:
      # 'fastapi-app' must match the container name in Docker Compose
      - targets: ['fastapi-app:9001']