name: 3 - Continuous Staging
run-name: "${{ github.workflow }}"

permissions: write-all

on:
  # Runs when the previous stage finished
  workflow_run:
    workflows: ["2 - Continuous Delivery"]
    types: [completed]

  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY }}
  MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
  MLFLOW_EXPERIMENT_NAME: ${{ vars.MLFLOW_EXPERIMENT_NAME }}
  MLFLOW_MODEL_NAME: ${{ vars.MLFLOW_MODEL_NAME }}

jobs:
  stage-tests:
    # Run only if previous stage finished successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - name: Setup python environment
        run: |
          pip install uv
          uv sync

      # Log in to GitHub Container Registry (GHCR)
      # We will get the serving image with tag staging from here to validate
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull serving and mlflow images
        run: |
          docker pull ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging

      # ===================== Setup VPN to access DEI network =====================
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Create OVPN file
        run: echo "${{ secrets.OVPN_CONFIG_FILE }}" > DEI.ovpn

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: DEI.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}

      - name: Ping test
        run: |
          set -x
          ping -c 4 ${{ secrets.SERVING_VM_HOST }} || echo "ping failed with code $?"

      # ===================== Setup serving container =====================
      - name: Save serving image to tar
        run: docker save ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging -o /tmp/serving_staging.tar

      - name: Copy serving image to staging VM
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVING_VM_HOST }}
          username: ${{ secrets.SERVING_VM_USERNAME }}
          password: ${{ secrets.SERVING_VM_PASSWORD }}
          source: /tmp/serving_staging.tar
          target: ~/docker_images
          strip_components: 1

      - name: Connect to DEI server via SSH and prepare environment
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SERVING_VM_HOST }}
          username: ${{ secrets.SERVING_VM_USERNAME }}
          password: ${{ secrets.SERVING_VM_PASSWORD }}
          script: |
            # Stop and remove existing serving container if running
            docker rm -f serving-app || true
            # Load the serving image from the transferred tar file
            docker load --input ~/docker_images/serving_staging.tar

      - name: Start serving container
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MODEL_ALIAS: ${{ github.sha }}
          MLFLOW_MODEL_NAME: ${{ env.MLFLOW_MODEL_NAME }}
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SERVING_VM_HOST }}
          username: ${{ secrets.SERVING_VM_USERNAME }}
          password: ${{ secrets.SERVING_VM_PASSWORD }}
          envs: MLFLOW_TRACKING_URI,MODEL_ALIAS,MLFLOW_MODEL_NAME
          script: |
            docker run -d \
              --name serving-app \
              -p 8080:8080 \
              -e MLFLOW_TRACKING_URI \
              -e MODEL_ALIAS \
              -e MLFLOW_MODEL_NAME \
              ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging

            # Wait for FastAPI to be ready
            sleep 10

      # ===================== Run tests against staging environment =====================
      # Here we are just running the same E2E tests, but in real systems we would run
      # the system in a preproduction environment, that would manually or automatically
      # apply  A/B testing, shadow testing and other approaches to measure
      # and validate the performance of the model before moving to production
      - name: Run Staging tests
        run: uv run pytest tests/test_e2e.py -v

      # When reaching the stage both the serving and the model will have passed
      # the necessary tests and we promote to production
      - name: Promote model to production
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          FROM_ALIAS: staging
          TO_ALIAS: production
        run: uv run python model-promotion/promote_model.py

      # Tag the serving image with production tag
      # This is the image that will be used to deploy the system
      - name: Push production container tag
        run: |
          docker tag ${{ env.REGISTRY }}/${{ github.repository }}/serving:staging \
                     ${{ env.REGISTRY }}/${{ github.repository }}/serving:production
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/serving:production
