name: 4 - Continuous Deployment
run-name: "${{ github.workflow }}"

permissions: write-all

on:
  # Runs when the previous stage finished
  workflow_run:
    workflows: ["3 - Continuous Staging"]
    types: [completed]

  workflow_dispatch:

env:
  REGISTRY: ${{ vars.REGISTRY }}
  MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
  MLFLOW_EXPERIMENT_NAME: ${{ vars.MLFLOW_EXPERIMENT_NAME }}
  MLFLOW_MODEL_NAME: ${{ vars.MLFLOW_MODEL_NAME }}

jobs:
  deploy-prod:
    # Run only if previous stage finished successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Here we are just loging in to GHCR and pulling the serving image with production tag and running it
      # In a real setup the deployment can be made in several ways, depending on the automation,
      # purpose, and infra. Some examples:
      # - We can connect through ssh and update the env
      # - if we have orchestrators we can send/define/update the new versions to where the system is watching
      # - the system itself might be monitoring repos and update when the new versions are pushed
      # Also, in real setups the infra will be decoupled from the models. Here everything moves forward together
      # but if we only change the model it is not necessary to redeploy the infrascruture. Serving frameworks
      # such as TF serving can manage model A/B testing, rollout, rollback, ...
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker pull ${{ env.REGISTRY }}/${{ github.repository }}/serving:production

      # ===================== Setup VPN to access DEI network =====================
      # Install OpenVPN
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      # Recreate the .ovpn file from the base64 secret
      - name: Create OVPN file
        run: echo "${{ secrets.OVPN_CONFIG_FILE }}" | base64 -d > DEI.ovpn

      # Create auth file for username/password
      - name: Create auth file
        run: |
          echo "${{ secrets.OVPN_USERNAME }}" > vpn-auth.txt
          echo "${{ secrets.OVPN_PASSWORD }}" >> vpn-auth.txt
          chmod 600 vpn-auth.txt

      # Start OpenVPN in the background
      - name: Connect to VPN via openvpn
        run: |
          sudo openvpn --config DEI.ovpn --auth-user-pass vpn-auth.txt --daemon
          sleep 15

      # Verify VPN
      - name: Verify VPN connection
        run: |
          if ip addr show tun0 >/dev/null 2>&1; then
            echo "VPN is up."
          else
            echo "VPN is NOT up. Exiting."
            exit 1
          fi

      - run: docker stop serving-app || true
      - run: docker rm serving-app || true

      - name: Run production
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MODEL_ALIAS: ${{ github.sha }}
          MLFLOW_MODEL_NAME: ${{ env.MLFLOW_MODEL_NAME }}
        run: |
          docker run -d --name serving-app -p 9000:8080 \
            -e MLFLOW_TRACKING_URI \
            -e MODEL_ALIAS \
            -e MLFLOW_MODEL_NAME \
          ${{ env.REGISTRY }}/${{ github.repository }}/serving:production
