[project]
name = "models"
version = "0.1.0"
requires-python = ">=3.13.7"
dependencies = [
    "boto3>=1.42.6",
    "joblib>=1.5.2",
    "mlflow>=3.7.0",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.3",
]
